# Inspired by https://github.com/antfu/.github
contact_links:
  - name: ğŸ™Œ Contribution Guide
    url: https://github.com/prazdevs/pinia-plugin-persistedstate/blob/main/CONTRIBUTING.md
    about: Please read through before making contributions.
  - name: â‰ï¸ Why and How to make a reproduction?
    url: https://antfu.me/posts/why-reproductions-are-required
    about: A great article by Anthony Fu (@antfu) on why reproduction is very important for maintainer to help on your issues!
